"""
Django settings for lucky_forums project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# BUILD PATHS INSIDE THE PROJECT LIKE THIS: BASE_DIR / 'SUBDIR'.
BASE_DIR = Path(__file__).resolve().parent.parent


# QUICK-START DEVELOPMENT SETTINGS - UNSUITABLE FOR PRODUCTION
# SEE HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/HOWTO/DEPLOYMENT/CHECKLIST/

# SECURITY WARNING: KEEP THE SECRET KEY USED IN PRODUCTION SECRET!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-i4we@j&zg5(64o)i%(+6m@p%o2ovcl2*b&!ykk*0z(3qyoxn6$",
)

# SECURITY WARNING: DON'T RUN WITH DEBUG TURNED ON IN PRODUCTION!
DEBUG = config("DEBUG", cast=bool, default=True)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default="")


# APPLICATION DEFINITION

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3RD PARTY
    "rest_framework",
    # LOCAL
    "forum",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "users.middleware.BanBlockMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lucky_forums.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lucky_forums.wsgi.application"


# DATABASE
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/REF/SETTINGS/#DATABASES

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB", default="file_forum"),
        "USER": config("POSTGRES_USER", default="file_forum_user"),
        "PASSWORD": config("POSTGRES_PASSWORD", default="file_forum_pass"),
        "HOST": config("POSTGRES_HOST", default="localhost"),
        "PORT": config("POSTGRES_PORT", default="5432"),
    }
}


# PASSWORD VALIDATION
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/REF/SETTINGS/#AUTH-PASSWORD-VALIDATORS

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# INTERNATIONALIZATION
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/TOPICS/I18N/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# STATIC FILES (CSS, JAVASCRIPT, IMAGES)
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/HOWTO/STATIC-FILES/

STATIC_URL = "static/"

# MEDIA FILES
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# DEFAULT PRIMARY KEY FIELD TYPE
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/REF/SETTINGS/#DEFAULT-AUTO-FIELD

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH REDIRECTS
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/auth/login/"

# DJANGO REST FRAMEWORK
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("users.permissions.NotBanned",),
}
